name: ted
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0
- backports=1.0
- backports.functools_lru_cache=1.4
- blas=1.1
- bleach=2.0.0
- ca-certificates=2017.11.5
- certifi=2017.11.5
- cycler=0.10.0
- decorator=4.1.2
- entrypoints=0.2.3
- freetype=2.8.1
- html5lib=1.0.1
- icu=58.2
- ipykernel=4.7.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.1
- jedi=0.11.1
- jinja2=2.10
- jpeg=9b
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.2
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- libgfortran=3.0.0
- libpng=1.6.34
- libsodium=1.0.15
- markupsafe=1.0
- matplotlib=2.1.2
- mistune=0.8.3
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- notebook=5.4.0
- numpy=1.14.0
- openblas=0.2.20
- openssl=1.0.2n
- pandas=0.22.0
- pandoc=2.1.1
- pandocfilters=1.4.1
- parso=0.1.1
- pexpect=4.3.1
- pickleshare=0.7.4
- pip=9.0.1
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- pygments=2.2.0
- pyparsing=2.2.0
- pyqt=5.6.0
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.3.1
- readline=7.0
- scipy=1.0.0
- send2trash=1.4.2
- setuptools=38.4.0
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- sqlite=3.20.1
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- tornado=4.5.3
- traitlets=4.3.2
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.1.3
- xz=5.2.3
- zeromq=4.2.1
- zlib=1.2.11
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15


