name: TEDECT
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0
- backports.functools_lru_cache=1.4
- ca-certificates=2017.11.5
- certifi=2017.11.5
- freetype=2.8.1
- openssl=1.0.2n
- psycopg2=2.7.3.1
- python=3.6.4
- python-dateutil=2.6.1
- send2trash=1.4.2
- configparser=3.5.0
- unidecode=1.0.23
- pip:
  - backports.functools-lru-cache==1.4
  - psycopg2==2.7.3.1
  - tweepy==3.6.0
